python train_centralDA_source.py --domain_s 'realworld' --domain_u 'art' --model_name resnet50 --d_mode new --device cuda:0 --var_lr 0.03  --scheduler_name  'ExponentialLR' --cycles 50   --control_name "1_sup-ft-fix_15_0.3_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  
python train_centralDA_source.py --domain_s 'art' --domain_u 'clipart' --model_name resnet50 --d_mode new --device cuda:0 --var_lr 0.03  --scheduler_name  'ExponentialLR' --cycles 50   --control_name "1_sup-ft-fix_15_0.3_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  
python train_centralDA_source.py --domain_s 'art' --domain_u 'clipart' --model_name resnet50 --d_mode new --device cuda:0 --var_lr 0.03  --scheduler_name  'ExponentialLR' --cycles 250   --control_name "2_sup-ft-fix_15_0.3_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  


python train_centralDA_source.py --domain_s 'art' --domain_u 'clipart' --model_name VITs --d_mode new --device cuda:1 --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50   --control_name "1_sup-ft-fix_15_0.3_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  --backbone_arch vit-small

python train_classifier_ssDA_target.py --domain_s 'art' --unsup_doms 'product-clipart-realworld'  --model_name VITs  --d_mode new --device cuda:1  --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "4001_sup-ft-fix_15_0.3_iid_5-5_0.07_1" --resume_mode  1  --init_seed 2020 --run_shot 1 --par 1 --tag_ "2020_art_0.03_VITs_1_sup-ft-fix"  --client_test 1 --pick 'best' --add_fix 0   --backbone_arch vit-small  

python train_classifier_ssDA_target.py --domain_s 'art' --unsup_doms 'product-clipart-realworld'  --model_name VITs  --d_mode new --device cuda:0  --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "500011_sup-ft-fix_15_0.3_iid_5-5_0.07_1" --resume_mode  1  --init_seed 2020 --run_shot 1 --par 1 --tag_ "2020_art_0.03_VITs_1_sup-ft-fix"  --client_test 1 --pick 'best' --add_fix 0   --backbone_arch vit-small  --var_reg True  --var_wt 0.1 

python train_classifier_ssDA_target_plot.py --domain_s 'art' --unsup_doms 'product-clipart-realworld'  --model_name VITs  --d_mode new --device cuda:0  --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "4001_sup-ft-fix_15_0.3_iid_5-5_0.07_1" --resume_mode_target   1  --init_seed 2020 --run_shot 1 --par 1 --tag_ "2020_art_0.03_VITs_1_sup-ft-fix"  --client_test 1 --pick 'best'   --backbone_arch vit-small  


python train_classifier_ssDA_target_crco.py --domain_s 'art' --unsup_doms 'product-clipart-realworld'  --model_name VITs  --d_mode new --device cuda:1  --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "111001_sup-ft-fix_15_0.3_iid_5-5_0.07_1" --resume_mode  1  --init_seed 2020 --run_shot 1 --par 1 --tag_ "2020_art_0.03_VITs_1_sup-ft-fix"  --client_test 1 --pick 'best'  --backbone_arch vit-small --run_crco 1 --add_fix 1     --lambda 0.9 --g_lambda 0.1   --global_reg 1  --threshold 0.80 --var_reg True --var_wt 0.1
python train_classifier_ssDA_target_crco.py --domain_s 'art' --unsup_doms 'product-clipart-realworld'  --model_name VITs  --d_mode new --device cuda:0  --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "001_sup-ft-fix_15_0.3_iid_5-5_0.07_1" --resume_mode  1  --init_seed 2020 --run_shot 1 --par 1 --tag_ "2020_art_0.03_VITs_1_sup-ft-fix"  --client_test 1 --pick 'best'  --backbone_arch vit-small --run_crco 1 