

python train_classifier_ssDA_target.py --domain_s 'webcam' --unsup_doms 'dslr-amazon'  --model_name resnet50 --d_mode new --device  cuda:0   --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "001117_sup-ft-fix_6_0.5_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  --run_shot 1    --par 1 --tag_ "2020_webcam_0.03_resnet50_2_sup-ft-fix"  --client_test 1 --pick 'checkpoint' --add_fix 1 --multi_model 0    --lambda 1 --g_lambda 1  --var_wt 0.001  --global_reg 1 --var_reg True  
python train_classifier_ssDA_target.py --domain_s 'amazon' --unsup_doms 'dslr-webcam'  --model_name resnet50 --d_mode new --device  cuda:0   --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "001117_sup-ft-fix_6_0.5_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  --run_shot 1    --par 1 --tag_ "2020_amazon_0.03_resnet50_2_sup-ft-fix"  --client_test 1 --pick 'checkpoint' --add_fix 1 --multi_model 0    --lambda 1 --g_lambda 1  --var_wt 0.001  --global_reg 1 --var_reg True    
python train_classifier_ssDA_target.py --domain_s 'dslr' --unsup_doms 'amazon-webcam'  --model_name resnet50 --d_mode new --device  cuda:0   --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "001117_sup-ft-fix_6_0.5_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  --run_shot 1    --par 1 --tag_ "2020_dslr_0.03_resnet50_2_sup-ft-fix"  --client_test 1 --pick 'checkpoint' --add_fix 1 --multi_model 0    --lambda 1 --g_lambda 1  --var_wt 0.001  --global_reg 1 --var_reg True 


python train_classifier_ssDA_target.py --domain_s 'webcam' --unsup_doms 'dslr-amazon'  --model_name resnet50 --d_mode new --device  cuda:0   --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "001118_sup-ft-fix_6_0.5_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  --run_shot 1    --par 1 --tag_ "2020_webcam_0.03_resnet50_2_sup-ft-fix"  --client_test 1 --pick 'checkpoint' --add_fix 1 --multi_model 0    --lambda 0.5 --g_lambda 0.5  --var_wt 0.001  --global_reg 1 --var_reg True  
python train_classifier_ssDA_target.py --domain_s 'amazon' --unsup_doms 'dslr-webcam'  --model_name resnet50 --d_mode new --device  cuda:0   --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "001118_sup-ft-fix_6_0.5_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  --run_shot 1    --par 1 --tag_ "2020_amazon_0.03_resnet50_2_sup-ft-fix"  --client_test 1 --pick 'checkpoint' --add_fix 1 --multi_model 0    --lambda 0.5 --g_lambda 0.5  --var_wt 0.001  --global_reg 1 --var_reg True    
python train_classifier_ssDA_target.py --domain_s 'dslr' --unsup_doms 'amazon-webcam'  --model_name resnet50 --d_mode new --device  cuda:0   --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "001118_sup-ft-fix_6_0.5_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  --run_shot 1    --par 1 --tag_ "2020_dslr_0.03_resnet50_2_sup-ft-fix"  --client_test 1 --pick 'checkpoint' --add_fix 1 --multi_model 0    --lambda 0.5 --g_lambda 0.5  --var_wt 0.001  --global_reg 1 --var_reg True 

