python train_centralDA_sourceOC.py --data_name 'DomainNetS' --domain_s 'infograph' --data_name_unsup 'DomainNetS' --domain_u 'clipart'  --model_name VITs --d_mode new --device cuda:0 --var_lr 0.1 --scheduler_name  'CosineAnnealingLR' --cycles 50   --control_name "991_sup-ft-fix_8_0.5_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  --backbone_arch vit-small 
python train_classifier_ssDA_target_DN.py --data_name 'DomainNetS'  --data_name_unsup 'DomainNetS'  --domain_s 'infograph' --unsup_doms 'clipart-quickdraw-real-sketch-painting'  --model_name VITs --d_mode new --device cuda:0  --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "99001_sup-ft-fix_10_0.3_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  --run_shot 1  --par 1 --tag_ "2020_infograph_0.1_VITs_991_sup-ft-fix"  --client_test 1 --pick 'checkpoint'  --backbone_arch vit-small 
python train_classifier_ssDA_target_DN.py --data_name 'DomainNetS'  --data_name_unsup 'DomainNetS'  --domain_s 'infograph' --unsup_doms 'clipart-quickdraw-real-sketch-painting'  --model_name VITs --d_mode new --device cuda:0  --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "99001111_sup-ft-fix_10_0.3_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  --run_shot 1  --par 1 --tag_ "2020_infograph_0.1_VITs_991_sup-ft-fix"  --client_test 1 --pick 'checkpoint'  --backbone_arch vit-small --add_fix 1 --multi_model 0    --lambda 3 --g_lambda 0.3   --global_reg 1  --threshold 0.8  --var_reg True  --var_wt 0.001  


python train_classifier_ssDA_target_DN.py --data_name 'DomainNetS'  --data_name_unsup 'DomainNetS'  --domain_s 'infograph' --unsup_doms 'clipart-quickdraw-real-sketch-painting'  --model_name VITs  --d_mode new --device cuda:2  --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "9911133_sup-ft-fix_15_0.3_iid_5-5_0.07_1" --resume_mode  1  --init_seed 2020 --run_shot 0  --run_hcld 0 --par 1 --tag_ "2020_infograph_0.1_VITs_1_sup-ft-fix" --client_test 1 --pick 'checkpoint' --backbone_arch vit-small --add_fix 1   --lambda 6  --adpt_thr 1  --client_test 1 --g_lambda 3 --global_reg 1  --threshold 0.8 --run_UCon 1
python train_classifier_ssDA_target_DN.py --data_name 'DomainNetS'  --data_name_unsup 'DomainNetS'  --domain_s 'infograph' --unsup_doms 'clipart-quickdraw-real-sketch-painting'  --model_name VITs  --d_mode new --device cuda:3  --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "9900133_sup-ft-fix_15_0.3_iid_5-5_0.07_1" --resume_mode  1  --init_seed 2020 --run_shot 0  --run_hcld 0 --par 1 --tag_ "2020_infograph_0.1_VITs_1_sup-ft-fix" --client_test 1 --pick 'checkpoint' --backbone_arch vit-small --add_fix 0   --lambda 3  --adpt_thr 0  --client_test 1 --g_lambda 3 --global_reg 0  --threshold 0.8 --run_UCon 1

python train_classifier_ssDA_target_DN.py --data_name 'DomainNetS'  --data_name_unsup 'DomainNetS'  --domain_s 'quickdraw' --unsup_doms 'clipart-infograph-real-sketch-painting'  --model_name VITs  --d_mode new --device cuda:1  --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "9911133_sup-ft-fix_15_0.3_iid_5-5_0.07_1" --resume_mode  1  --init_seed 2020 --run_shot 0  --run_hcld 0 --par 1 --tag_ "2020_quickdraw_0.03_VITs_1_sup-ft-fix" --client_test 1 --pick 'checkpoint' --backbone_arch vit-small --add_fix 1   --lambda 3  --adpt_thr 1  --client_test 1 --g_lambda 0.3 --global_reg 1  --threshold 0.8 --run_UCon 1
python train_classifier_ssDA_target_DN.py --data_name 'DomainNetS'  --data_name_unsup 'DomainNetS'  --domain_s 'quickdraw' --unsup_doms 'clipart-infograph-real-sketch-painting'  --model_name VITs  --d_mode new --device cuda:1  --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "9900133_sup-ft-fix_15_0.3_iid_5-5_0.07_1" --resume_mode  1  --init_seed 2020 --run_shot 0  --run_hcld 0 --par 1 --tag_ "2020_quickdraw_0.03_VITs_1_sup-ft-fix" --client_test 1 --pick 'checkpoint' --backbone_arch vit-small --add_fix 0   --lambda 3  --adpt_thr 0  --client_test 1 --g_lambda 3 --global_reg 0  --threshold 0.8 --run_UCon 1

python train_classifier_ssDA_target_DN.py --data_name 'DomainNetS'  --data_name_unsup 'DomainNetS'  --domain_s 'clipart' --unsup_doms 'infograph-quickdraw-real-sketch-painting'  --model_name VITs  --d_mode new --device cuda:0  --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "9911133_sup-ft-fix_15_0.3_iid_5-5_0.07_1" --resume_mode  1  --init_seed 2020 --run_shot 0  --run_hcld 0 --par 1 --tag_ "2020_clipart_0.1_VITs_1_sup-ft-fix" --client_test 1 --pick 'checkpoint' --backbone_arch vit-small --add_fix 1   --lambda 3  --adpt_thr 1  --client_test 1 --g_lambda 3 --global_reg 1  --threshold 0.8 --run_UCon 1
python train_classifier_ssDA_target_DN.py --data_name 'DomainNetS'  --data_name_unsup 'DomainNetS'  --domain_s 'clipart' --unsup_doms 'infograph-quickdraw-real-sketch-painting'  --model_name VITs  --d_mode new --device cuda:1  --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "9900133_sup-ft-fix_15_0.3_iid_5-5_0.07_1" --resume_mode  1  --init_seed 2020 --run_shot 0  --run_hcld 0 --par 1 --tag_ "2020_clipart_0.1_VITs_1_sup-ft-fix" --client_test 1 --pick 'checkpoint' --backbone_arch vit-small --add_fix 0   --lambda 3  --adpt_thr 0  --client_test 1 --g_lambda 3 --global_reg 0  --threshold 0.8 --run_UCon 1

python train_classifier_ssDA_target_DN.py --data_name 'DomainNetS'  --data_name_unsup 'DomainNetS'  --domain_s 'painting' --unsup_doms 'clipart-infograph-quickdraw-real-sketch'  --model_name VITs  --d_mode new --device cuda:0  --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "9911133_sup-ft-fix_15_0.3_iid_5-5_0.07_1" --resume_mode  1  --init_seed 2020 --run_shot 0  --run_hcld 0 --par 1 --tag_ "2020_painting_0.1_VITs_1_sup-ft-fix" --client_test 1 --pick 'checkpoint' --backbone_arch vit-small --add_fix 1   --lambda 3  --adpt_thr 1  --client_test 1 --g_lambda 3 --global_reg 1  --threshold 0.8 --run_UCon 1

python train_classifier_ssDA_target_DN.py --data_name 'DomainNetS'  --data_name_unsup 'DomainNetS'  --domain_s 'painting' --unsup_doms 'clipart-infograph-quickdraw-real-sketch'  --model_name VITs  --d_mode new --device cuda:1  --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "9900133_sup-ft-fix_15_0.3_iid_5-5_0.07_1" --resume_mode  1  --init_seed 2020 --run_shot 0  --run_hcld 0 --par 1 --tag_ "2020_painting_0.1_VITs_1_sup-ft-fix" --client_test 1 --pick 'checkpoint' --backbone_arch vit-small --add_fix 0   --lambda 3  --adpt_thr 0  --client_test 1 --g_lambda 3 --global_reg 0  --threshold 0.8 --run_UCon 1

python train_classifier_ssDA_target_DN.py --data_name 'DomainNetS'  --data_name_unsup 'DomainNetS'  --domain_s 'real' --unsup_doms 'clipart-infograph-quickdraw-painting-sketch'  --model_name VITs  --d_mode new --device cuda:0  --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "9911133_sup-ft-fix_15_0.3_iid_5-5_0.07_1" --resume_mode  1  --init_seed 2020 --run_shot 0  --run_hcld 0 --par 1 --tag_ "2020_real_0.03_VITs_1_sup-ft-fix" --client_test 1 --pick 'checkpoint' --backbone_arch vit-small --add_fix 1   --lambda 6  --adpt_thr 1  --client_test 1 --g_lambda 3 --global_reg 1  --threshold 0.8 --run_UCon 1
python train_classifier_ssDA_target_DN.py --data_name 'DomainNetS'  --data_name_unsup 'DomainNetS'  --domain_s 'real' --unsup_doms 'clipart-infograph-quickdraw-painting-sketch'  --model_name VITs  --d_mode new --device cuda:1  --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "9900133_sup-ft-fix_15_0.3_iid_5-5_0.07_1" --resume_mode  1  --init_seed 2020 --run_shot 0  --run_hcld 0 --par 1 --tag_ "2020_real_0.03_VITs_1_sup-ft-fix" --client_test 1 --pick 'checkpoint' --backbone_arch vit-small --add_fix 0   --lambda 6  --adpt_thr 0  --client_test 1 --g_lambda 3 --global_reg 0  --threshold 0.8 --run_UCon 1

python train_classifier_ssDA_target_DN.py --data_name 'DomainNetS'  --data_name_unsup 'DomainNetS'  --domain_s 'sketch' --unsup_doms 'clipart-infograph-quickdraw-painting-real'  --model_name VITs  --d_mode new --device cuda:0  --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "9911133_sup-ft-fix_15_0.3_iid_5-5_0.07_1" --resume_mode  1  --init_seed 2020 --run_shot 0  --run_hcld 0 --par 1 --tag_ "2020_sketch_0.03_VITs_1_sup-ft-fix" --client_test 1 --pick 'checkpoint' --backbone_arch vit-small --add_fix 1   --lambda 6  --adpt_thr 1  --client_test 1 --g_lambda 3 --global_reg 1  --threshold 0.8 --run_UCon 1
python train_classifier_ssDA_target_DN.py --data_name 'DomainNetS'  --data_name_unsup 'DomainNetS'  --domain_s 'sketch' --unsup_doms 'clipart-infograph-quickdraw-painting-real'  --model_name VITs  --d_mode new --device cuda:1  --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "9900133_sup-ft-fix_15_0.3_iid_5-5_0.07_1" --resume_mode  1  --init_seed 2020 --run_shot 0  --run_hcld 0 --par 1 --tag_ "2020_sketch_0.03_VITs_1_sup-ft-fix" --client_test 1 --pick 'checkpoint' --backbone_arch vit-small --add_fix 0   --lambda 6  --adpt_thr 0  --client_test 1 --g_lambda 3 --global_reg 0  --threshold 0.8 --run_UCon 1
