
python train_classifier_ssDA_target_DN.py --data_name 'DomainNet'  --data_name_unsup 'DomainNet'  --domain_s 'clipart' --unsup_doms 'infograph-quickdraw-real-sketch-painting'  --model_name resnet50 --d_mode new --device cuda:0  --var_lr 0.01  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "100001_sup-ft-fix_25_0.2_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  --run_shot 0  --par 1 --tag_ "2020_clipart_0.03_resnet50_1_sup-ft-fix"  --client_test 1 --pick 'checkpoint' --add_fix 1 
python train_classifier_ssDA_target_DN.py --data_name 'DomainNet'  --data_name_unsup 'DomainNet' --domain_s 'infograph' --unsup_doms 'clipart-quickdraw-real-sketch-painting'  --model_name resnet50 --d_mode new --device cuda:0  --var_lr 0.01  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "100001_sup-ft-fix_25_0.2_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  --run_shot 0  --par 1 --tag_ "2020_infograph_0.03_resnet50_1_sup-ft-fix"  --client_test 1 --pick 'checkpoint'  --add_fix 1 
python train_classifier_ssDA_target_DN.py --data_name 'DomainNet'  --data_name_unsup 'DomainNet'  --domain_s 'quickdraw' --unsup_doms 'infograph-clipart-real-sketch-painting'  --model_name resnet50 --d_mode new --device cuda:0  --var_lr 0.01  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "100001_sup-ft-fix_25_0.2_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  --run_shot 0  --par 1 --tag_ "2020_quickdraw_0.03_resnet50_1_sup-ft-fix"  --client_test 1 --pick 'checkpoint'  --add_fix 1 
python train_classifier_ssDA_target_DN.py --data_name 'DomainNet'  --data_name_unsup 'DomainNet'  --domain_s 'real' --unsup_doms 'infograph-quickdraw-clipart-sketch-painting'  --model_name resnet50 --d_mode new --device cuda:0  --var_lr 0.01  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "100001_sup-ft-fix_25_0.2_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  --run_shot 0  --par 1 --tag_ "2020_real_0.03_resnet50_2_sup-ft-fix"  --client_test 1 --pick 'checkpoint'  --add_fix 1 
python train_classifier_ssDA_target_DN.py --data_name 'DomainNet'  --data_name_unsup 'DomainNet'  --domain_s 'sketch' --unsup_doms 'infograph-clipart-real-quickdraw-painting'  --model_name resnet50 --d_mode new --device cuda:0  --var_lr 0.01  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "100001_sup-ft-fix_25_0.2_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  --run_shot 0  --par 1 --tag_ "2020_sketch_0.03_resnet50_1_sup-ft-fix"  --client_test 1 --pick 'checkpoint'  --add_fix 1 
python train_classifier_ssDA_target_DN.py --data_name 'DomainNet'  --data_name_unsup 'DomainNet'  --domain_s 'painting' --unsup_doms 'infograph-clipart-real-sketch-quickdraw'  --model_name resnet50 --d_mode new --device cuda:0  --var_lr 0.01  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "100001_sup-ft-fix_25_0.2_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  --run_shot 0  --par 1 --tag_ "2020_painting_0.03_resnet50_1_sup-ft-fix"  --client_test 1 --pick 'checkpoint'  --add_fix 1 



python train_classifier_ssDA_target_DN.py --data_name 'DomainNet'  --data_name_unsup 'DomainNet'  --domain_s 'clipart' --unsup_doms 'infograph-quickdraw-real-sketch-painting'  --model_name VITs --d_mode new --device cuda:0  --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "100001_sup-ft-fix_25_0.2_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  --run_shot 0  --par 1 --tag_ "2020_clipart_0.03_VITs_33_sup-ft-fix"  --client_test 1 --pick 'checkpoint' --add_fix 1  --backbone_arch vit-b 

python train_classifier_ssDA_target_DN.py --data_name 'DomainNetS'  --data_name_unsup 'DomainNetS'  --domain_s 'clipart' --unsup_doms 'infograph-quickdraw-real-sketch-painting'  --model_name VITs --d_mode new --device cuda:1  --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "001_sup-ft-fix_10_0.3_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  --run_shot 0  --par 1 --tag_ "2020_clipart_0.03_VITs_1_sup-ft-fix"  --client_test 1 --pick 'checkpoint'  --backbone_arch vit-b

python train_classifier_ssDA_target_DN.py --data_name 'DomainNetS'  --data_name_unsup 'DomainNetS'  --domain_s 'clipart' --unsup_doms 'infograph-quickdraw-real-sketch-painting'  --model_name VITs --d_mode new --device cuda:0  --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 1  --control_name "001_sup-ft-fix_10_1_iid_50-50_0.07_1" --resume_mode 1  --init_seed 2020  --run_shot 1  --par 1 --tag_ "2020_clipart_0.1_VITs_1_sup-ft-fix"  --client_test 1 --pick 'checkpoint'  --backbone_arch vit-b

python train_classifier_ssDA_target_DN.py --data_name 'DomainNetS'  --data_name_unsup 'DomainNetS'  --domain_s 'clipart' --unsup_doms 'infograph-quickdraw-real-sketch-painting'  --model_name VITs --d_mode new --device cuda:1  --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "001103_sup-ft-fix_10_0.3_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  --run_shot 1  --par 1 --tag_ "2020_clipart_0.1_VITs_1_sup-ft-fix"  --client_test 1 --pick 'checkpoint'  --backbone_arch vit-b --add_fix 1 --multi_model 0    --lambda 0.9 --g_lambda 0.1   --global_reg 1  
python train_classifier_ssDA_target_DN.py --data_name 'DomainNetS'  --data_name_unsup 'DomainNetS'  --domain_s 'clipart' --unsup_doms 'infograph-quickdraw-real-sketch-painting'  --model_name VITs --d_mode new --device cuda:1  --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "001105_sup-ft-fix_10_0.3_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  --run_shot 1  --par 1 --tag_ "2020_clipart_0.1_VITs_1_sup-ft-fix"  --client_test 1 --pick 'ch
eckpoint'  --backbone_arch vit-b --add_fix 1 --multi_model 0    --lambda 0.9 --g_lambda 0.1   --global_reg 1  --threshold 0.98