


python train_classifier_ssDA_target.py --domain_s 'amazon' --unsup_doms 'dslr-webcam'  --model_name VITs --d_mode new --device  cuda:0 --var_lr 0.001 --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "0001114_sup-ft-fix_6_0.5_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  --run_shot 1  --par 1 --tag_ "2020_amazon_0.03_VITs_2_sup-ft-fix"  --client_test 1     --pick 'checkpoint' --add_fix 1 --multi_model 0   --backbone_arch vit-small  --lambda 1 --g_lambda 1  --var_wt 0.1  --global_reg 1 --var_reg True   
python train_classifier_ssDA_target.py --domain_s 'webcam' --unsup_doms 'dslr-amazon'  --model_name VITs --d_mode new --device  cuda:0 --var_lr 0.001  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "0001114_sup-ft-fix_6_0.5_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  --run_shot 1  --par 1 --tag_ "2020_webcam_0.03_VITs_2_sup-ft-fix"  --client_test 1     --pick 'checkpoint' --add_fix 1 --multi_model 0   --backbone_arch vit-small  --lambda 1 --g_lambda 1  --var_wt 0.1  --global_reg 1 --var_reg True   
python train_classifier_ssDA_target.py --domain_s 'dslr' --unsup_doms 'amazon-webcam'  --model_name VITs --d_mode new --device  cuda:0 --var_lr 0.001  --scheduler_name  'CosineAnnealingLR' --cycles520  --control_name "0001114_sup-ft-fix_6_0.5_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  --run_shot 1  --par 1 --tag_ "2020_dslr_0.03_VITs_2_sup-ft-fix"  --client_test 1     --pick 'checkpoint' --add_fix 1 --multi_model 0   --backbone_arch vit-small  --lambda 1 --g_lambda 1  --var_wt 0.1  --global_reg 1 --var_reg True   

python train_classifier_ssDA_target.py --domain_s 'amazon' --unsup_doms 'dslr-webcam'  --model_name VITs --d_mode new --device  cuda:0 --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "001_sup-ft-fix_6_0.5_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  --run_shot 1 --par 1 --tag_ "2020_amazon_0.03_VITs_2_sup-ft-fix"  --client_test 1 --pick 'checkpoint' --add_fix 0  --cluster 0   --backbone_arch vit-small 
python train_classifier_ssDA_target.py --domain_s 'webcam' --unsup_doms 'dslr-amazon'  --model_name VITs --d_mode new --device  cuda:0 --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "001_sup-ft-fix_6_0.5_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  --run_shot 1 --par 1 --tag_ "2020_webcam_0.03_VITs_2_sup-ft-fix"  --client_test 1 --pick 'checkpoint' --add_fix 0  --cluster 0   --backbone_arch vit-small 
python train_classifier_ssDA_target.py --domain_s 'dslr' --unsup_doms 'amazon-webcam'  --model_name VITs --d_mode new --device  cuda:0 --var_lr 0.03  --scheduler_name  'CosineAnnealingLR' --cycles 50  --control_name "001_sup-ft-fix_6_0.5_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  --run_shot 1 --par 1 --tag_ "2020_dslr_0.03_VITs_2_sup-ft-fix"  --client_test 1 --pick 'checkpoint' --add_fix 0  --cluster 0   --backbone_arch vit-small 


python train_classifier_ssDA_target.py --domain_s 'amazon' --unsup_doms 'dslr-webcam'  --model_name VITs --d_mode new --device cuda:0  --var_lr 0.01  --scheduler_name  'CosineAnnealingLR' --cycles 1  --control_name "40001_sup-ft-fix_6_1_iid_40-40_0.07_1" --resume_mode 1  --init_seed 2020  --run_shot 1 --par 1 --tag_ "2020_amazon_0.03_VITs_2_sup-ft-fix"  --client_test 1 --pick 'checkpoint' --add_fix 0  --cluster 0  --backbone_arch vit-small  >>1.txt
python train_classifier_ssDA_target.py --domain_s 'webcam' --unsup_doms 'dslr-amazon'  --model_name VITs --d_mode new --device cuda:0  --var_lr 0.01  --scheduler_name  'CosineAnnealingLR' --cycles 1  --control_name "40001_sup-ft-fix_6_1_iid_40-40_0.07_1" --resume_mode 1  --init_seed 2020  --run_shot 1 --par 1 --tag_ "2020_webcam_0.03_VITs_2_sup-ft-fix"  --client_test 1 --pick 'checkpoint' --add_fix 0  --cluster 0  --backbone_arch vit-small >>2.txt
python train_classifier_ssDA_target.py --domain_s 'dslr' --unsup_doms 'amazon-webcam'  --model_name VITs --d_mode new --device cuda:0  --var_lr 0.01  --scheduler_name  'CosineAnnealingLR' --cycles 1  --control_name "40001_sup-ft-fix_6_1_iid_40-40_0.07_1" --resume_mode 1  --init_seed 2020  --run_shot 1 --par 1 --tag_ "2020_dslr_0.03_VITs_2_sup-ft-fix"  --client_test 1 --pick 'checkpoint' --add_fix 0  --cluster 0 --backbone_arch vit-small >>3.txt

python train_classifier_ssDA_target.py --domain_s 'amazon' --unsup_doms 'dslr-webcam'  --model_name VITs --d_mode new --device  cuda:0 --var_lr 0.01  --scheduler_name  'CosineAnnealingLR' --cycles 30  --control_name "002_sup-ft-fix_6_0.5_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  --run_shot 1 --par 1 --tag_ "2020_amazon_0.03_VITs_2_sup-ft-fix"  --client_test 1 --pick 'checkpoint' --add_fix 0  --cluster 0   --backbone_arch vit-small 
python train_classifier_ssDA_target.py --domain_s 'webcam' --unsup_doms 'dslr-amazon'  --model_name VITs --d_mode new --device  cuda:0 --var_lr 0.01  --scheduler_name  'CosineAnnealingLR' --cycles 30  --control_name "002_sup-ft-fix_6_0.5_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  --run_shot 1 --par 1 --tag_ "2020_webcam_0.03_VITs_2_sup-ft-fix"  --client_test 1 --pick 'checkpoint' --add_fix 0  --cluster 0   --backbone_arch vit-small 
python train_classifier_ssDA_target.py --domain_s 'dslr' --unsup_doms 'amazon-webcam'  --model_name VITs --d_mode new --device  cuda:0 --var_lr 0.01  --scheduler_name  'CosineAnnealingLR' --cycles 30  --control_name "002_sup-ft-fix_6_0.5_iid_5-5_0.07_1" --resume_mode 1  --init_seed 2020  --run_shot 1 --par 1 --tag_ "2020_dslr_0.03_VITs_2_sup-ft-fix"  --client_test 1 --pick 'checkpoint' --add_fix 0  --cluster 0   --backbone_arch vit-small 